android-core/src/main/java/com/mparticle/MParticle.java, android-kit-base/src/main/java/com/mparticle/kits/KitIntegrationFactory.java
This PR adds references for Carnival kit. It does not add Gradle settings/submodules.
=> Add Carnival Kit

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/release.yml
- Fix release job last step and update PR template doc
- Release job should run successfully
=> ci: update PR template and fix release job sync step

release.config.js
Fix bad formatting in previous semantic release PR. Testing has to be done from the main branch, so this couldn't have been vetted until after the previous PR was already merged 
run release
Closes https://go.mparticle.com/work/75621
=> fix: bad formatting in release.config.js

release.config.js
Missed one rewording "scope" -> "release"
Run release
Closes https://go.mparticle.com/work/same-as-previous-pr
=> fix: typo in release.config.js

.github/workflows/daily.yml
- Add dry run to fix daily cron job
- Tests should pass
Closes https://go.mparticle.com/work/78096
=> fix: add dry run to fix daily cron health check job

.github/workflows/cross-platform-tests.yml
- Fix cross platforms for Android forked PRs when checking out code
- Tests should pass
Closes https://go.mparticle.com/work/78239
=> fix: Fix cross platforms for Android forked PRs when checking out code

.github/workflows/release.yml
- add gpg signing to mparticle-automation commits
- future semantic releases commits should be verified
- Closes https://go.mparticle.com/work/SQDSDKS-3600
=> feat: add gpg signing to mparticle-automation commits

.github/workflows/release.yml
- update test kit command in release.yml
- release job should work
- Closes https://go.mparticle.com/work/SQDSDKS-3708
=> fix: update test kit command in release.yml

README.md
Update README's firebase code sample for BOM, add optional iid dependency
-tested manually 
- Closes https://go.mparticle.com/work/SQDSDKS-3647
=> chore: update README firebase code sample

android-core/proguard.pro
- Add missing proguard statement
- existing _release_ tests now pass
- Closes https://go.mparticle.com/work/SQDSDKS-3984
=> fix: add missing proguard statement

.github/workflows/daily.yml, .github/workflows/release.yml, .github/workflows/sonarcloud.yml
- update release and daily check job
- release should pass
=> ci: update release and daily check job

.github/workflows/daily.yml, .github/workflows/release.yml
- add in environment token in daily job
- release job should pass
=> fix: add in environment token in daily job

.github/workflows/daily.yml, .github/workflows/release.yml
- pass in secret to release regression job & fix daily job check
- release job should pass
=> fix: pass in secret to release regression job

.github/workflows/release.yml
- fix broken release yml
- run release job
=> fix: dry run param

.github/workflows/release.yml, release.config.js
- add in release notes generator updates
- add in release notes generator updates
- Closes https://go.mparticle.com/work/SQDSDKS-4028
=> ci: add in release notes generator updates

.github/workflows/daily.yml
- update semantic release job in daily check
- daily check job should pass
- Closes https://go.mparticle.com/work/SQDSDKS-4046
=> fix: update semantic release job in daily check

android-core/src/main/java/com/mparticle/MParticle.java, android-core/src/main/java/com/mparticle/MParticleOptions.java, android-core/src/main/java/com/mparticle/internal/database/services/MParticleDBManager.java, android-core/src/main/java/com/mparticle/internal/database/services/UploadService.java
- add client side rules
- test in sample app editing one event batch
- Closes https://go.mparticle.com/work/SQDSDKS-3734
=> feat: add client side rules

android-core/src/androidTest/kotlin/com.mparticle/BatchCreationCallbackTests.kt, android-core/src/main/java/com/mparticle/internal/database/services/MParticleDBManager.java
- change default batch creation error logic
- batch tests should pass
- Closes https://go.mparticle.com/work/SQDSDKS-4076
=> fix: change default batch creation error logic

.github/dependabot.yml, .github/workflows/dependabot-automerge.yml, .github/workflows/pull-request.yml, .github/workflows/release.yml
- Use github.com's recommend workaround for `pull_request_target` PWN issue
- forked PR tests should still run
- Closes https://go.mparticle.com/work/SQDSDKS-4055
=> fix: update dependabot token for pull_request

.github/dependabot.yml, .github/workflows/dependabot-automerge.yml, ONBOARDING.md
- Filter automerge should only happen for dependabot user
- Dependabot automerge should work
- Closes https://go.mparticle.com/work/SQDSDKS-4182
=> fix: clean up dependabot step

.github/dependabot.yml, .github/workflows/dependabot-automerge.yml, android-kit-base/src/main/kotlin/com/mparticle/kits/DataplanFilter.kt, build.gradle, tooling/custom-lint-rules/src/main/java/com/mparticle/lints/Extensions.kt
- upgrade sonarqube to 3.4 and kotlin to 1.7.10
- regression tests should all pass
- Closes https://go.mparticle.com/work/SQDSDKS-4304
=> feat: upgrade sonarqube to 3.4 and kotlin to 1.7.10

android-core/src/main/java/com/mparticle/MParticleOptions.java, android-core/src/main/java/com/mparticle/internal/MParticleApiClient.java
- Expose MParticleOptions.Builder#logLevel and AliasNetworkResponse so they can be consumed by crossplatform testing
- this branch passes in the sdk-multiplatform-tests repo
- Closes https://go.mparticle.com/work/SQDSDKS-4366
=> refactor: update visibility for crossplatform testing

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/daily.yml, .github/workflows/pull-request.yml, android-core/build.gradle, android-core/src/main/java/com/mparticle/MParticle.java
- add new SharedPreferences files to MParticle.reset()
- add orchestrator tests to GHA job
- existing tests pass, orchestrator tests pass
- Closes https://go.mparticle.com/work/SQDSDKS-4365
=> fix: reset logic, fixing orchestrator

android-core/build.gradle, gradle/wrapper/gradle-wrapper.properties, testutils/build.gradle, tooling/custom-lint-rules/build.gradle
- Update Gradle wrapper blocking Android 13 work
- Update various other dependencies triggered from dependabot
- Regression tests should pass
- Closes https://go.mparticle.com/work/SQDSDKS-4512
=> feat: update dependencies for Android 13 (from dependabot)

.github/workflows/release.yml, README.md
- add in missing GPG step for updating submodules
- regression tests should pass
- Closes https://go.mparticle.com/work/SQDSDKS-4552
=> ci: add in missing GPG step for updating submodules

.github/workflows/release.yml, android-core/build.gradle, android-core/src/androidTest/AndroidManifest.xml, android-core/src/androidTest/java/com/mparticle/MParticleTest.java, android-core/src/androidTest/java/com/mparticle/WebViewActivity.java, android-core/src/androidTest/java/com/mparticle/internal/MParticleJSInterfaceITest.java, android-core/src/main/AndroidManifest.xml, android-kit-base/build.gradle, android-kit-base/src/androidTest/AndroidManifest.xml, android-kit-base/src/main/AndroidManifest.xml, build.gradle, gradle.properties, kit-plugin/build.gradle, kit-plugin/src/main/groovy/com/mparticle/kits/KitPlugin.groovy, testutils/build.gradle, testutils/src/androidTest/AndroidManifest.xml, testutils/src/main/AndroidManifest.xml
- bump up compile SDK to 33
- bump up ktlint version
- regression tests should all pass except crossplatforms (we'll need a PR to update AGP there)
- Closes https://go.mparticle.com/work/SQDSDKS-4523
=> feat: bump up compile SDK and ktlint version

README.md, build.gradle, release.config.js
- Update copy in readme for android 13
- regression tests should pass (minus crossplatforms since AGP isn't updated there yet)
- Closes https://go.mparticle.com/work/SQDSDKS-4649
=> docs: Update copy in readme for android 13

.github/workflows/cross-platform-tests.yml, .github/workflows/daily.yml, .github/workflows/pull-request.yml, .github/workflows/release.yml, .github/workflows/sonarcloud.yml
- update github actions that are deprecated (set-output warnings are from another repo)
- regression suite should pass
- Closes https://go.mparticle.com/work/SQDSDKS-4621
=> ci: Update github actions that are deprecated

testutils/build.gradle
- Upgrade worked on rerun.
- All regresion test should pass.
- Closes https://go.mparticle.com/work/SQDSDKS-4743
=> feat: Investigate dependabot automerge Mockito library upgrade.

.github/workflows/sonarcloud.yml, android-core/src/main/java/com/mparticle/MPServiceUtil.java, android-core/src/main/java/com/mparticle/messaging/MPMessagingAPI.java, build.gradle
- Update sonarcloud job
- Regression tests should pass
- Closes https://go.mparticle.com/work/SQDSDKS-4766
=> ci: Fix sonarcloud job for forked repos

.github/workflows/daily.yml, .github/workflows/pull-request.yml, .github/workflows/release.yml, android-core/build.gradle, android-kit-base/src/main/java/com/mparticle/kits/KitConfiguration.java, build.gradle, kit-plugin/build.gradle, kit-plugin/src/main/groovy/com/mparticle/kits/KitPlugin.groovy, kit-plugin/src/test/groovy/com/mparticle/kits/KitPluginTest.groovy, testutils/build.gradle
- Add in ktlintCheck to daily cron job
- Add in a few dependabot passing changes
- Regression tests should pass
- Closes https://go.mparticle.com/work/SQDSDKS-4870
=> ci: Add in ktlintCheck to daily cron job

.github/workflows/pull-request.yml, .github/workflows/release.yml, .mobsf, .semgrepignore, android-core/src/main/java/com/mparticle/internal/MParticleJSInterface.java, android-core/src/main/java/com/mparticle/internal/database/services/MessageService.java, android-core/src/main/java/com/mparticle/internal/listeners/InternalListenerManager.java, android-core/src/main/java/com/mparticle/networking/NetworkConnection.java, android-kit-base/src/main/java/com/mparticle/kits/KitIntegrationFactory.java, gradlew, scripts/install-start-emulator.sh, scripts/kits/merge-updates.sh, scripts/kits/update.sh, scripts/release.sh
- Added semgrep and mobsf scans to pull requests
- Marked all false positives in-code and add in exceptions for test files
- Escape bash variables with quotes
- Letting the new test run here do the work...
- Closes https://go.mparticle.com/work/SQDSDKS-4990
=> ci: Add semgrep, mobsf static analysis

android-core/src/androidTest/kotlin/com.mparticle/MParticleTest.kt, android-core/src/main/java/com/mparticle/MParticle.java, android-core/src/test/kotlin/com/mparticle/external/ApiVisibilityTest.kt, testutils/src/main/java/com/mparticle/testutils/BaseCleanStartedEachTest.java
- Adding method to change update interval after initialization, exposed in MParticle
- Unit tests added
- Closes https://mparticle-eng.atlassian.net/browse/SQDSDKS-4947
[SQDSDKS-4947]: https://mparticle-eng.atlassian.net/browse/SQDSDKS-4947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Adding method to change update interval after initialization

android-core/src/androidTest/kotlin/com.mparticle/MParticleOptionsTest.kt, android-core/src/androidTest/kotlin/com.mparticle/MParticleTest.kt, android-core/src/main/java/com/mparticle/MParticle.java, android-core/src/main/java/com/mparticle/MParticleOptions.java, android-core/src/main/kotlin/com.mparticle/WrapperSdk.kt, android-core/src/test/kotlin/com/mparticle/MParticleTest.kt, android-core/src/test/kotlin/com/mparticle/external/ApiVisibilityTest.kt
Adding wrapperSdk in MParticleOptions and MParticle
- Adding WrapperSdk enum as definition. Creating abstraction WrapperSdkVersion which contains the WrapperSdk and version.
Add WrapperSdkVersion in MParticle. The default value is NONE with version null, after using the setter to change it to a valid sdkWrapper with a non-null and non-empty version; cant be set again in the same instance (this is a Singleton)
Added tests for different scenarios.
- Added …
=> feat: Adding WrapperSdk, WrapperSdkVersion - adding this values to MParticleOptions and MParticle

android-core/build.gradle, android-core/src/main/java/com/mparticle/modernization/MParticleCallback.kt, android-core/src/main/java/com/mparticle/modernization/Utils.kt, android-core/src/main/java/com/mparticle/modernization/config/UploadingConfiguration.kt, android-core/src/main/java/com/mparticle/modernization/core/MParticle.kt, android-core/src/main/java/com/mparticle/modernization/core/MParticleComponent.kt, android-core/src/main/java/com/mparticle/modernization/core/MParticleMediator.kt, android-core/src/main/java/com/mparticle/modernization/data/MParticleDataRepository.kt, android-core/src/main/java/com/mparticle/modernization/eventlogging/MParticleEventLogging.kt, android-core/src/main/java/com/mparticle/modernization/eventlogging/example/MParticleEventLoggingImpl.kt, android-core/src/main/java/com/mparticle/modernization/identity/IdentityCallback.kt, android-core/src/main/java/com/mparticle/modernization/identity/MParticleIdentity.kt, android-core/src/main/java/com/mparticle/modernization/identity/example/MParticleIdentityImpl.kt, android-core/src/main/java/com/mparticle/modernization/kit/MParticleKit.kt, android-core/src/main/java/com/mparticle/modernization/kit/MParticleKitManager.kt, android-core/src/main/java/com/mparticle/modernization/kit/MParticleKitManagerImpl.kt, android-core/src/main/java/com/mparticle/modernization/kit/example/CustomKit.kt, android-core/src/main/java/com/mparticle/modernization/kit/example/MpKit.kt, android-core/src/main/java/com/mparticle/modernization/kit/example/XKit.kt, android-core/src/main/java/com/mparticle/modernization/uploading/MParticleDataUploader.kt, android-core/src/main/java/com/mparticle/modernization/uploading/MParticleDataUploaderImpl.kt, android-core/src/main/java/com/mparticle/modernization/uploading/MParticleUploadingStrategy.kt, android-core/src/main/java/com/mparticle/modernization/uploading/example/MParticleBreadcrumbUploading.kt, android-core/src/main/java/com/mparticle/modernization/uploading/example/MParticleUploaderTypes.kt, android-kit-base/src/main/kotlin/com/mparticle/kits/DataplanFilter.kt
- {provide a thorough description of the changes}
=> feat: dev into main

android-core/src/main/java/com/mparticle/MParticleOptions.java, android-kit-base/src/main/java/com/mparticle/kits/KitIntegrationFactory.java, android-kit-base/src/main/java/com/mparticle/kits/KitManagerImpl.java, android-kit-base/src/main/java/com/mparticle/kits/LocalKit.java, android-kit-base/src/test/kotlin/com/mparticle/kits/KitManagerImplTest.kt, android-kit-base/src/test/kotlin/com/mparticle/kits/KitManagerTest.kt, testutils/src/main/java/com/mparticle/mock/MockKitIntegrationFactory.java, testutils/src/main/java/com/mparticle/mock/MockKitManagerImpl.java
Adding local kit as a wrapper for config and kit integration.
Creating empty config based on a random unused Int generated by the factory. 
Adding kit merging and initializing.
- Closes https://mparticle-eng.atlassian.net/browse/SQDSDKS-5112
=> feat: sideloading kits

.github/workflows/pull-request.yml, android-core/src/androidTest/kotlin/com.mparticle/BatchCreationCallbackTests.kt, android-core/src/main/java/com/mparticle/MParticle.java, android-core/src/main/java/com/mparticle/MParticleOptions.java, android-kit-base/src/main/java/com/mparticle/kits/KitConfiguration.java, android-kit-base/src/test/kotlin/com/mparticle/kits/KitConfigurationTest.kt, testutils/src/main/java/com/mparticle/testutils/MPLatch.java
=> fix kit submodule

android-core/src/androidTest/kotlin/com.mparticle/MParticleOptionsTest.kt, android-core/src/androidTest/kotlin/com.mparticle/networking/AccessUtils.kt, android-core/src/androidTest/kotlin/com.mparticle/networking/MParticleBaseClientImplTest.kt, android-core/src/androidTest/kotlin/com.mparticle/networking/NetworkOptionsManagerTest.kt, android-core/src/androidTest/kotlin/com.mparticle/networking/NetworkOptionsTest.kt, android-core/src/main/java/com/mparticle/MParticleOptions.java, android-core/src/main/java/com/mparticle/internal/ConfigManager.java, android-core/src/main/java/com/mparticle/networking/DomainMapping.java, android-core/src/main/java/com/mparticle/networking/MParticleBaseClientImpl.java, android-core/src/main/java/com/mparticle/networking/NetworkOptions.java, android-core/src/main/java/com/mparticle/networking/NetworkOptionsManager.java, testutils/src/main/java/com/mparticle/networking/MockServer.java
- Changes for pod specific redirection
- Closes https://mparticle-eng.atlassian.net/browse/SQDSDKS-5770
=> feat: Adding pod specific redirection based on prefix

android-kit-base/src/main/java/com/mparticle/kits/FilteredMParticleUser.java
- Updated consent method implementation
- 
- Verified through compilation and execution of a local application.
- Closes https://go.mparticle.com/work/SQDSDKS-6176
=> fix : Update consent method implementation

.github/workflows/cross-platform-tests.yml, .github/workflows/pull-request.yml, android-core/build.gradle, android-core/src/androidTest/kotlin/com.mparticle/MPUserTest.kt, android-kit-base/build.gradle, kit-plugin/build.gradle, kit-plugin/src/main/groovy/com/mparticle/kits/KitPlugin.groovy
- update JDK version from 11 to 17 and change macos configuration
=> fix: Update mac version and JDK version into yml file

.github/workflows/release.yml
Redoing #484 against the main branch, since it's YML file changes.
update java version from 11 to 17
=> fix: update java version into release yml file

.github/workflows/daily.yml
- change Instrumented Test script command for JDK 17 update
- -yml file changes, so can not test locally.
=> fix: Update Run Instrumented Tests command

.github/workflows/daily.yml, .github/workflows/release.yml
- Update Java version to 17, pin conventional commits to 7
This is combining    
-  #485 
-  #486
-  #487
-  #488 
-  #489
-yml file changes, so can not test locally.
=> fix: Update Java version, pin conventional commits

android-core/src/main/java/com/mparticle/MParticle.java
- Add enum values for event types
- Tested with sample application and executed unit tests
- Closes https://go.mparticle.com/work/SQDSDKS-6544
=> fix: Add enum value for event types

build.gradle
-  cherry-pick commit https://github.com/mParticle/mparticle-android-sdk/pull/532
- Tested these changes with a sample app and ran the unit tests.
- Closes https://go.mparticle.com/work/SQDSDKS-6952
=> fix: Update Kotlin version to be compatible with Braze (#532)

.github/workflows/daily.yml
- Removed the 'Test Kits' step from the GitHub workflow.
- Closes https://go.mparticle.com/work/SQDSDKS-6280
=> ci: Update GitHub workflow to remove Test Kits step

.gitmodules, settings-kits.gradle
- Include rokt as a submodule
- Closes https://go.mparticle.com/work/SQDSDKS-7154
=> chore: Add rokt submodule

.github/workflows/daily.yml
- Adds a new step to the GitHub Actions workflow to run or include Test Kits during the CI process. This helps ensure test coverage and reliability of the integration.
=> ci: Add Test Kits step to GitHub workflow

android-core/proguard.pro, android-core/src/main/java/com/mparticle/MParticle.java, android-core/src/main/java/com/mparticle/internal/KitFrameworkWrapper.java, android-core/src/main/java/com/mparticle/internal/KitManager.java, android-core/src/test/kotlin/com/mparticle/MParticleTest.kt, android-kit-base/src/main/java/com/mparticle/kits/KitIntegration.java, android-kit-base/src/main/java/com/mparticle/kits/KitManagerImpl.java, android-kit-base/src/test/kotlin/com/mparticle/kits/KitManagerImplTest.kt
- This PR is to add callback support to the MParticle Rokt API's
=> feat: Added Callback Support

android-kit-base/build.gradle, android-kit-base/src/main/java/com/mparticle/kits/KitManagerImpl.java, android-kit-base/src/test/kotlin/com/mparticle/kits/KitManagerImplTest.kt
- This PR adds logic to check the email passed to MParticle.Rokt.selectPlacements. Check if that email matches the one in the current mParticle user identity. If the email is missing or different, use the Identity modify API to update the email in the user's identity.
- Tested with sample app and executed test cases.
- Closes https://go.mparticle.com/work/SQDSDKS-7248
=> feat: Fire Identify if Provided Email in Rokt SelectPlacements

.github/workflows/pull-request.yml
- Add concurrency settings to cancel in-progress runs
- Add explicit permissions
- Add --info flag to Gradle commands for better logging
- Add PR notification to GChat
- N/A
=> chore: Update GitHub Actions workflow

scripts/maven.gradle
- This PR migrates our artifact publishing workflow from OSSRH (The Open Source Software Repository Hosting) to the new Central Publishing Portal (CPP) as per the updated guidelines from Sonatype.
Guideline : https://central.sonatype.org/news/20250326_ossrh_sunset/
- Closes https://go.mparticle.com/work/SQDSDKS-7479
=> chore: Migrate from OSSRH to Central Publishing Portal

CONTRIBUTING.md, README.md, RELEASE.md
- Updated README.md with consistent formatting. Added CONTRIBUTING.md to define contribution guidelines. Added RELEASING.md to document the release process.To standardize documentation structure with other repositories.
=> docs: Updated readme file and add contributing and release file
