mParticle/mparticle-android-sdk

- README.md
- android-core/src/main/java/com/mparticle/internal/KitFrameworkWrapper.java
- android-core/src/main/java/com/mparticle/internal/MParticleApiClientImpl.java
- android-core/src/main/java/com/mparticle/messaging/MPMessagingRouter.java
- android-core/src/main/java/com/mparticle/messaging/PushAnalyticsReceiver.java
- android-core/src/main/java/com/mparticle/messaging/PushAnalyticsReceiverCallback.java
- android-core/src/test/java/com/mparticle/internal/KitFrameworkWrapperTest.java
- android-core/src/test/java/com/mparticle/internal/MParticleApiClientImplTest.java
- android-kit-base/src/main/java/com/mparticle/kits/KitConfiguration.java
Core changes:
- `PushAnalyticsReceiver#onNotification*` methods are now part of an interface (`PushAnalyticsReceiverCallback`)
- `PushAnalyticsReceiver` now delegates processing of the intent and calling of callbacks into `MPMessagingRouter`
- `MPMessagingRouter` abides by a contract of only consuming what it should, and lets the caller know if the given `Intent` was consumed
> Moving MParticle-specific messaging logic into a router for reusability

- .github/workflows/release.yml
- release.config.js
Add explicit versioning rules for all the valid commit prefixes we use
Reword kit update commit message to be prefixed with `"ci:` so that semantic release only does a patch update
Run release job
Closes https://go.mparticle.com/work/75621
> fix: Update Semantic release configurations

- .github/workflows/pull-request.yml
Remove step running lint on kits from our PR CI checks.
existing tests pass, this is a net removal
Closes https://go.mparticle.com/work/77624
> ci: Remove Kit lint checks for Pull Requests

- android-core/src/androidTest/java/com/mparticle/identity/IdentityApiStartTest.java
- android-core/src/main/java/com/mparticle/internal/DeviceAttributes.java
- android-core/src/main/java/com/mparticle/internal/MPUtility.java
This adds a missing check for whether we should collect and include the AndroidId in Identity requests
updated existing checks to ensure that AndroidId is not collected when `isAndroidIdDisabled() == true`
Closes https://mparticle.tpondemand.com/restui/board.aspx?#page=bug/77526&boardPopup=userstory/77585
> fix: Add additional checks for AndroidId

- android-core/src/androidTest/java/com/mparticle/MParticleOptionsTest.java
- android-core/src/androidTest/kotlin/com.mparticle/internal/ConfigStalenessCheckTest.kt
- android-core/src/main/java/com/mparticle/MParticle.java
- android-core/src/main/java/com/mparticle/MParticleOptions.java
- android-core/src/main/java/com/mparticle/internal/ConfigManager.java
- android-core/src/main/java/com/mparticle/internal/MParticleApiClientImpl.java
- android-core/src/test/java/com/mparticle/internal/ConfigManagerTest.java
- android-core/src/test/java/com/mparticle/internal/DeviceAttributesTest.java
- android-core/src/test/java/com/mparticle/internal/LoggerTest.java
- android-core/src/test/java/com/mparticle/internal/MParticleApiClientImplTest.java
- android-core/src/test/java/com/mparticle/internal/MessageBatchTest.java
- android-kit-base/src/androidTest/kotlin/com/mparticle/kits/KitManagerImplTests.kt
- testutils/src/main/java/com/mparticle/mock/MockConfigManager.java
- testutils/src/main/java/com/mparticle/networking/Matcher.java
- testutils/src/main/java/com/mparticle/networking/MockServer.java
(moved from internal repo)
Add public API for setting a max config staleness parameter. If the config is older than staleness limit, we will delete it instead of loading it from memory while we wait for the new config
```
val options = MParticleOptions.builder(context)
.maxConfigAge(1000 * 60 * 60 * 24 * 7)                   <- set a max age of 1 week
.build()
```
note: **maxConfigAge value is ~DAYS~ SECONDS**
- **not setting** maxConfigAge will default it to `null` which means it will **not** take effect and the SDK will behave exactly how it currently does
- setting it to **a negative Integer** will trigger a warning-level log message then proceed as if it was `null` (same as above)
- setting it to `0` will result in the stored config being deleted every time the SDK starts up aka Kits …
> feat: Add configMaxAge to MParticleOptions

- .github/workflows/cross-platform-tests.yml
- .github/workflows/daily.yml
- .github/workflows/pull-request.yml
- .github/workflows/reusable-workflows.yml
- Add a daily android health check cron job (for releases)
- Running cron from workflow dispatch should pass
- Closes https://go.mparticle.com/work/77650
> ci: create first version of daily android health check cron job

- android-core/src/androidTest/java/com/mparticle/MParticleOptionsTest.java
- android-core/src/androidTest/kotlin/com.mparticle/internal/ConfigStalenessCheckTest.kt
- android-core/src/main/java/com/mparticle/MParticleOptions.java
- android-core/src/main/java/com/mparticle/internal/ConfigManager.java
update configMaxAge field type from `Long` -> `int`. This will limit the client's ability to set a maximum config age threshold to 24,855 days, but that seems like a reasonable maximum in retrospect
updated existing tests
Closes https://go.mparticle.com/work/77698
> fix: Change configMaxAge type from Long to int

- android-kit-base/src/main/java/com/mparticle/kits/KitUtils.java
Add getAndroidId() method implementation for kits
existing tests
Closes https://go.mparticle.com/work/77833
> refactor: Add getAndroidId method for Kits

- .github/workflows/pull-request.yml
- allow PR branch names that don't exist in origin repo.  This was a bug for forked repos
- CI tests should pass
Closes https://go.mparticle.com/work/77993
> ci: allow PR branch names that don't exist in origin repo

- android-core/src/androidTest/java/com/mparticle/MParticleOptionsTest.java
- android-core/src/androidTest/java/com/mparticle/identity/IdentityApiStartTest.java
- android-core/src/androidTest/java/com/mparticle/internal/DeviceAttributesTests.java
- android-core/src/main/java/com/mparticle/MParticle.java
- android-core/src/main/java/com/mparticle/MParticleOptions.java
- android-core/src/test/java/com/mparticle/external/ApiVisibilityTest.java
Change the default value for `MParticleOptions.isAndroidIdDisabled()` and `MParticle.isAndroidIdDisabled()` to `true`. Previously the default was false.
The net result will be that any client (including existing clients) who do not explicitly call `MParticleOptions.Builder.androidIdDisabled(Boolean)` will see the SDK behavior change. Previously, for these clients, we included Android ID as a `known_identities` entry in Identity Requests as well as a Device Attribute field in Batch Messages, but with this change we will only do so if they set `androidIdDisabled(true)` when building `MParticleOptions`
We have deprecated `MParticleOptions#isAndroIdDisabled()` and `MParticle.isAndroidIdDisabled()`. These methods were replaced by`MParticleOptions#isAndroidIdEnabled()` and …
> feat: Android id disabled default true

- android-core/build.gradle
- android-core/src/main/java/com/mparticle/MParticle.java
- android-core/src/main/java/com/mparticle/identity/IdentityApi.java
- android-kit-base/build.gradle
- build.gradle
- update java docs syntax after gradle upgrade
- CI tests should pass and javadocs should also generate
Closes https://go.mparticle.com/work/78794
> fix: update java docs syntax after gradle upgrade

- android-core/src/main/java/com/mparticle/MParticle.java
This error message is causing some confusion with implementors and is easily triggered by our internal code in non-error states. I think this information can still be useful for debugging future issues, so we will downgrade the severity from `error` -> `debug`
existing tests, superficial change
https://github.com/mParticle/mparticle-android-sdk/issues/66
Closes https://go.mparticle.com/work/80864
> fix: downgrade error log to debug

- .github/workflows/daily.yml
- .github/workflows/pull-request.yml
- .github/workflows/release.yml
Fix the configuration of our "Archive Unit Test Results" step. Previously we were _printing_ the results to the console, but failing to archive the files
Closes https://go.mparticle.com/work/80837
> ci: fix archive unit test results step

- android-core/src/androidTest/java/com/mparticle/PushRegistrationTest.java
- android-core/src/androidTest/java/com/mparticle/internal/ConfigManagerInstrumentedTest.java
- android-core/src/androidTest/kotlin/com.mparticle/internal/ConfigMigrationTest.kt
- android-core/src/androidTest/kotlin/com.mparticle/internal/ConfigStalenessCheckTest.kt
- android-core/src/main/java/com/mparticle/MParticle.java
- android-core/src/main/java/com/mparticle/internal/ConfigManager.java
- android-core/src/main/java/com/mparticle/internal/MPUtilityKotlin.kt
- android-core/src/main/java/com/mparticle/internal/MessageManager.java
- android-core/src/test/java/com/mparticle/internal/ConfigManagerTest.java
- testutils/src/main/java/com/mparticle/mock/MockApplication.java
- testutils/src/main/java/com/mparticle/mock/MockContext.java
- testutils/src/main/java/com/mparticle/networking/MockServer.java
- testutils/src/main/java/com/mparticle/testutils/BaseAbstractTest.java
`SharedPreferences` loads pretty slow. Worse than that, it seems to grow linearly with the overall size of the file. The edge cases where we see very slow startup time are generally in cases where the user has a large number of Kit filters or projections, which lead to a very large config (stored in `SharedPreferences`) and result in a slow loading time when we fetch our first pair from the file. Outside of the various Kit configuration properties, the rest of the config has a fairly low ceiling for how big it could possibly get.
Since we don't actually need the kit portion of the configuration at startup, it makes sense to store it outside of `SharedPreferences` so we can load _just_ the data we need at startup. This PR splits the config when it is fetched and continues to persist the …
> feat: split configuration into core and kits

- android-core/proguard.pro
In our current Proguard configuration, as long as one class is "kept", it will preserve the package name for all classes within. When there are **no** classes kept in a given package, proguard will remove the package alltogether. Unfortunatley we have one package, `com.mparticle.internal.database` which has no kept classes, so these package name is removed, which leaves these classes (obfuscated as `a.java`, `b.java`, etc) open to an east namespace collision.
My fix enables a default package of `com.mparticle`, so all classes will _at least_ be under the "com.mparticle" namespace
existing tests pass 
Closes https://go.mparticle.com/work/81502
https://github.com/mParticle/mparticle-android-sdk/issues/107
> fix: keep package names in proguard to prevent collisions

- android-kit-base/src/main/java/com/mparticle/kits/KitIntegrationFactory.java
- Fix typo in the GoogleAnalyticsFirebaseGAKit qualified class name. In its current state, the KitIntegrationFactory is unable to find the kit class
manually tested, I don't believe there is any way for us to unit test this effectively
- Closes https://go.mparticle.com/work/[81918](https://mparticle.tpondemand.com/RestUI/Board.aspx#page=userstory/81918&appConfig=eyJhY2lkIjoiMjM4RjY2OUU2RkYxNzFCMTVCMUU5Q0JCRDlFQzQyRTAifQ==)
> fix: typo in GA4 kit name

- android-core/src/main/java/com/mparticle/internal/Constants.java
- android-core/src/main/java/com/mparticle/internal/MParticleApiClientImpl.java
- android-core/src/main/java/com/mparticle/internal/MessageBatch.java
- release.config.js
- add etag to batch upload
- make sure sdk doesn't break in a sample app with new key (server should ignore for now)
- Closes https://go.mparticle.com/work/81946
> fix: add etag to batch upload payload

- android-core/build.gradle
- android-core/src/androidTest/java/com/mparticle/identity/MParticleIdentityClientImplTest.java
testModifyMessage() is one of our flakier tests and I found this is in part due to some asynchronous writed to `SharedPreferences`. In this test, we are making multiple updates to the same mpid/user, which is not required for the test case. This update simply changes the user each iteration so we do not need to account for the async updates
existing tests pass
- Closes https://go.mparticle.com/work/SQDSDKS-3571
> ci: improve instrumented test consistency 

- .github/workflows/pull-request.yml
- .github/workflows/release.yml
- android-core/proguard.pro
- android-core/src/main/java/com/mparticle/internal/BackgroundTaskHandler.java
- android-core/src/main/java/com/mparticle/internal/MessageManager.java
- android-core/src/main/java/com/mparticle/internal/UploadHandler.java
- android-core/src/test/java/com/mparticle/internal/KitFrameworkWrapperTest.java
- android-kit-base/src/main/java/com/mparticle/kits/KitIntegration.java
- android-kit-base/src/main/java/com/mparticle/kits/KitManagerImpl.java
- android-kit-base/src/test/java/com/mparticle/kits/KitManagerImplTest.java
- testutils/src/main/java/com/mparticle/mock/MockKitManagerImpl.java
Our last release failed because I missed a progaurd update in our last change which broke kits & kit-base in release builds.
This PR:
- fixes the missed proguard update
- fully removes a few usages of `BackgroundTaskHandler` that I missed
- adds a job in our PR GHA to test kits & kit-base against a release build of the current branch. Note, this will **only** run for pull requests
added additional tests to make sure these kinds of bugs are caught during PR
- Closes https://go.mparticle.com/work/SQDSDKS-3593
> fix: Proguard keeps KitsLoadedCallback

- android-kit-base/src/main/java/com/mparticle/kits/KitManagerImpl.java
- android-kit-base/src/main/java/com/mparticle/kits/ReportingMessage.java
- Add in missing projection fields
- Test a sample app that connects to a workspace that has custom mapping fields.  `af_content_view` should show up in timeline
- Closes https://go.mparticle.com/work/SQDSDKS-3404
> fix: add in missing projection fields

- .github/workflows/release.yml
I beleive the original change we made was unneeded, and as we've moved to fix the implementation error, we're basically just ending up with what we had originally. This PR fully rolls back the change made [here](https://github.com/mParticle/mparticle-android-sdk/pull/119/files#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34R114-R116)
- smoke tested locally 
- 
- Closes https://go.mparticle.com/work/SQDSDKS-3708
> ci: rollback extraneous release test change

- android-core/src/main/java/com/mparticle/internal/ConfigManager.java
- android-core/src/main/java/com/mparticle/internal/KitFrameworkWrapper.java
- android-core/src/main/java/com/mparticle/internal/KitManager.java
- android-core/src/test/java/com/mparticle/internal/ConfigManagerTest.java
- android-kit-base/src/androidTest/java/com/mparticle/kits/KnownUserKitsLifecycleTest.java
- android-kit-base/src/androidTest/kotlin/com/mparticle/kits/BaseKitOptionsTest.kt
- android-kit-base/src/androidTest/kotlin/com/mparticle/kits/KitManagerImplTests.kt
- android-kit-base/src/main/java/com/mparticle/kits/KitManagerImpl.java
- android-kit-base/src/test/java/com/mparticle/kits/KitManagerTest.java
Update the "x-mp-kits" header to include, not only kits actively receiving forwarding, but also kits that are configured but disabled due to client-side settings
- added unit test for header string generation and an End to End test
- Closes https://go.mparticle.com/work/SQDSDKS-3737
> fix: include stopped kits in active-kits header

- android-kit-base/src/main/java/com/mparticle/kits/ReportingMessage.java
This is a very small change that will be required for [this PR in the appboy/braze repo](https://github.com/mparticle-integrations/mparticle-android-integration-appboy/pull/71) to be merged in order to fully close out the linked ticket
Basically, we need to be able to send non-String attribute values to the server in order to accurately represent what we truly forwarded to Braze (non-string attribute values).
manually verified, not tests really needed as it is all compile-time checked
- Closes https://go.mparticle.com/work/SQDSDKS-3649
> refactor: allow non-string attribute keys for reporting messages

- tooling/custom-lint-rules/src/main/java/com/mparticle/lints/MParticleIssueRegistry.kt
I was testing the linter in a project and noticed that we are receiving a linter error due to this missing field. It looks like it became a required value at some point instead of falling back to the most recent API version
- manually tested
- Closes https://go.mparticle.com/work/SQDSDKS-4002
> fix: add value for api in custom lint IssueRegistry

- .github/workflows/release.yml
- change dependence from stable tag to branch in release job
- release job should pass
> fix: change dependence from stable tag to branch in release job

- android-core/src/androidTest/java/com/mparticle/MParticleOptionsTest.java
- android-core/src/androidTest/kotlin/com.mparticle/BatchCreationCallbackTests.kt
- android-core/src/main/java/com/mparticle/internal/Constants.java
- android-core/src/main/java/com/mparticle/internal/database/services/MParticleDBManager.java
- testutils/src/main/java/com/mparticle/testutils/TestingUtils.java
- Add E2E tests for the new BatchCreationListener endpoint
- added instrumented tests
- Closes https://go.mparticle.com/work/SQDSDKS-4066
> test: add BatchCreationListener integration tests

- android-core/src/main/java/com/mparticle/MPEvent.java
Rolling back removal of deprecated API's performed in PR #134 
It turns out that this method is relied on by a few of the wrapper SDKs and has been causing some compatibility issues (particularly in React Native). I’ve update those plugins but, to avoid compatibility issues between slightly older version of the RN SDK and the current Android SDK, I’m going to add the method back in
- integrates with old React Native versions (tested by hand)
- Closes https://go.mparticle.com/work/SQDSDKS-4074
> fix: rollback removal of MPEvent's info() methods

- android-core/src/main/java/com/mparticle/MPServiceUtil.java
- android-kit-base/src/androidTest/kotlin/com/mparticle/kits/BaseKitOptionsTest.kt
- android-kit-base/src/androidTest/kotlin/com/mparticle/kits/GCMPushMessageForwardingTest.kt
- android-kit-base/src/androidTest/kotlin/com/mparticle/kits/testkits/PushListenerTestKit.kt
- GCM Push Messages are being inadvertently ignored by the kit manager if the SDK has already been started. This was a regression introduced in [PR 118](https://github.com/mParticle/mparticle-android-sdk/pull/118), version 5.37.0
- 
- TODO, backfill tests, working on adding E2E tests to cover this scenario
- Closes https://go.mparticle.com/work/SQDSDKS-4116
> fix: forward foreground push messages to kit

- android-kit-base/src/androidTest/kotlin/com/mparticle/kits/KitBatchingTest.kt
- android-kit-base/src/androidTest/kotlin/com/mparticle/kits/testkits/EventTestKit.kt
- android-kit-base/src/main/java/com/mparticle/kits/KitConfiguration.java
- android-kit-base/src/main/java/com/mparticle/kits/KitManagerImpl.java
- Event attributes are being stringified somewhere before they land in the kits. These attributes should retain their original types and only be stringified when they are sent to the server. It appears that the issue is in our projection and mapping code, so it is possible we will need a wider fix for other paths events take (CommerceEvents, Screen events, projected events, etc). For now, this ticket will address the specifci known issue
- Added E2E test 
- Closes https://go.mparticle.com/work/SQDSDKS-4212
> fix: retain the original attribute value type when forwarded to kits

- android-core/src/androidTest/kotlin/com.mparticle/internal/UpdateAdIdIdentityTest.kt
- android-core/src/main/java/com/mparticle/identity/IdentityApi.java
- android-core/src/main/java/com/mparticle/internal/AppStateManager.java
- android-core/src/main/java/com/mparticle/internal/MParticleJSInterface.java
When the AdId updates, we will generate a modify() request interanlly with the current user. When the current user is not present/null, this request currently fails with an error log or a thrown exception, if the SDK is running in Development mode. In order to avoid losing this modify request or causing an exception, we will defer the modify request until a user is present, if it is not already
- added instrumented test, confirmed that it reproduces the error without any changes
- Closes https://go.mparticle.com/work/SQDSDKS-4270
> fix: modify() call throws an exception when user is not present

- android-core/src/main/java/com/mparticle/internal/ConfigManager.java
- Customer reported an odd issue where the kits are briefly initializing, de-initializing then re-initializing again on startup. I have been unable to reproduce, but based on the provided logs, it appears to be related to our migration logic released in v5.36.0. This fix adds a flag that ensures our migration logic _attempted_ exactly 1-time per device
- none at this time
- Closes https://go.mparticle.com/work/SQDSDKS-4265
> fix: config migration logic causes kits to deinit on re-upgrade

- android-core/build.gradle
- android-core/proguard.pro
- android-core/src/androidTest/java/com/mparticle/identity/MParticleUserDelegateITest.java
- android-core/src/androidTest/java/com/mparticle/internal/database/services/MParticleDBManagerTest.java
- android-core/src/androidTest/kotlin/com.mparticle/MPUserTest.kt
- android-core/src/main/java/com/mparticle/UserAttributeListener.java
- android-core/src/main/java/com/mparticle/identity/MParticleUser.java
- android-core/src/main/java/com/mparticle/identity/MParticleUserDelegate.java
- android-core/src/main/java/com/mparticle/identity/MParticleUserImpl.java
- android-core/src/main/java/com/mparticle/internal/KitFrameworkWrapper.java
- android-core/src/main/java/com/mparticle/internal/KitManager.java
- android-core/src/main/java/com/mparticle/internal/MPUtility.java
- android-core/src/main/java/com/mparticle/internal/MessageHandler.java
- android-core/src/main/java/com/mparticle/internal/MessageManager.java
- android-core/src/main/java/com/mparticle/internal/database/services/MParticleDBManager.java
- android-core/src/main/kotlin/com.mparticle/TypedUserAttributeListener.kt
- android-core/src/main/kotlin/com.mparticle/UserAttributeListenerType.kt
- android-core/src/main/kotlin/com/mparticle/identity/UserAttributeListenerWrapper.kt
- android-core/src/test/java/com/mparticle/identity/MParticleUserTest.java
- android-core/src/test/java/com/mparticle/internal/MPUtilityTest.java
- android-kit-base/src/androidTest/kotlin/com/mparticle/kits/testkits/UserAttributeListenerTestKit.kt
- android-kit-base/src/main/java/com/mparticle/kits/FilteredMParticleUser.java
- android-kit-base/src/main/java/com/mparticle/kits/KitIntegration.java
- android-kit-base/src/main/java/com/mparticle/kits/KitManagerImpl.java
- testutils/src/main/java/com/mparticle/mock/AbstractMParticleUser.java
… in line with iOS implementation
- Request to change incrementUserAttribute method signature to accept doubles to be consistent with iOS implementation
- https://github.com/mParticle/mparticle-apple-sdk/blob/main/mParticle-Apple-SDK/Identity/MParticleUser.m#L227
- Implicit type conversions should do most of the work, though maybe an overloaded incrementUserAttribute that uses int can be kept for legacy customers that rely on the data type of a user …
> fix: change incrementUserAttribute method signature to accept Number

- .github/workflows/cross-platform-tests.yml
- .github/workflows/daily.yml
- add needs statement and upgrade VMs
- regression tests should pass
- Closes https://go.mparticle.com/work/SQDSDKS-4376
> fix: add needs statement and upgrade VMs

- .github/PULL_REQUEST_TEMPLATE.md
- android-core/build.gradle
- build.gradle
- testutils/build.gradle
- tooling/custom-lint-rules/build.gradle
- Update to Kotlin 1.7.20
- Add in 3 necessary kit changes
- Add in new dependabot updates
- Regression tests should all pass (except crossplatforms since AGP 7.3.0 is not updated in that repo yet)
- Closes https://go.mparticle.com/work/SQDSDKS-4616
> ci: Update to kotlin 1.7.20

- android-core/src/main/java/com/mparticle/MPServiceUtil.java
- android-core/src/main/java/com/mparticle/messaging/ProviderCloudMessage.java
- Added pending intent flags.
- Test app no longer crashes on push notifications.
- Closes https://go.mparticle.com/work/SQDSDKS-4748
> fix: mParticle crashing on push notifications for android 12 and above.

- android-kit-base/src/main/java/com/mparticle/kits/FilteredMParticleUser.java
- Added null check for userAttribute value in FilteredMParticleUser.java onUserAttributesReceived(). 
- All CI test should pass.
- Closes https://go.mparticle.com/work/SQDSDKS-4875
> fix: Error handle null user attribute value

- .github/workflows/daily.yml
- android-core/src/androidTest/kotlin/com.mparticle/MPUserTest.kt
- android-core/src/main/java/com/mparticle/internal/MessageManager.java
- android-core/src/main/java/com/mparticle/internal/database/services/MParticleDBManager.java
- android-kit-base/src/main/java/com/mparticle/kits/FilteredMParticleUser.java
- build.gradle
- testutils/build.gradle
- testutils/src/main/java/com/mparticle/mock/AbstractMParticleUser.java
- tooling/custom-lint-rules/build.gradle
- Error handle null user attribute better and add use case to test file
- Add in dependabot updates
- Code clean up
- Regression tests should pass
- Closes https://go.mparticle.com/work/SQDSDKS-4891
> fix: Error handle null user attribute better and add use case to test file

- android-core/src/androidTest/kotlin/com.mparticle/BatchCreationCallbackTests.kt
- android-core/src/main/java/com/mparticle/MParticleOptions.java
- testutils/src/main/java/com/mparticle/testutils/MPLatch.java
- Adding the ability to drop batches by returning null
- Unit tests
- Closes https://mparticle-eng.atlassian.net/browse/SQDSDKS-5287
> fix: SQDSDKS-5287 unable to drop batches nullability

- android-core/src/main/java/com/mparticle/internal/ConfigManager.java
- android-core/src/main/java/com/mparticle/internal/KitFrameworkWrapper.java
Fixing initialization & de-initialization issue on kits.
- Have and Android app with at least one integration kit connected and added as a dependency, re-run app after first install and you will see in the logs De-initializing kit: <kit name>. This happens quite often about 50% of the time.
Configuration was done pararelly for core & kits.
If any kit was present with a null or empty string (then converted to a JsonObject), the active kits were …
> fix: Fixing initialization & de-initialization issue on kits.

- android-core/src/main/java/com/mparticle/internal/KitFrameworkWrapper.java
- android-kit-base/src/main/java/com/mparticle/kits/KitManagerImpl.java
Kit integration forwarding unplanned/blocked events when fired early on app run
- Dataplans was being updated before the config has been loaded, resulting on a race condition.
@mmustafa-tse was able to verify the fix.
- Closes https://mparticle-eng.atlassian.net/browse/SQDSDKS-5508
> fix: Kit integration forwarding unplanned/blocked events when fired early on app run

- android-core/src/main/java/com/mparticle/internal/ConfigManager.java
- android-core/src/main/java/com/mparticle/internal/KitFrameworkWrapper.java
Fix for Kit Initialization & De-Initializationg.
The underlying issues is that when the KitFrameworkManager calls fetchConfig, the kitConfig instance is null (the instance created not yet assigned). Therefore, the ApiClient can get the "supported kits" from the [KitManager.KitIntegrationFactory] and the mp-kit header is not added to the call, resulting in a response with "eks" empty. 
The fix includes assigning the KitManager instance before calling …
> fix: Kit Initialization & De-Initialization.

- .github/workflows/cross-platform-tests.yml
- android-core/src/main/java/com/mparticle/internal/Constants.java
- android-core/src/main/java/com/mparticle/internal/MPUtility.java
No need to remove user attribute limit since it wasn't implemented. Other limits (key and value length for user and custom attributes) remaing the same.
- Removing custom attributes limit
- Closes https://mparticle-eng.atlassian.net/browse/SQDSDKS-5723
> feat: SQDSDKS-5723 - Remove custom attributes limit to MPEvents.

- android-core/src/main/java/com/mparticle/InstallReferrerHelper.java
- SDK will only fetch the install referrer 1 time(app cold-start will not fetch)
-Verified through compilation and execution of a local application.
- Closes https://go.mparticle.com/work/SQDSDKS-6093
> fix: ANRs in android app due to multiple installReferrer API calls

- .github/workflows/release.yml
- update java version from 11 to 17 
> fix: update java version into release yml file

- .github/workflows/release.yml
- change conventional commits to version 7, there was major version bump to  8 on 5/03/2024, which seems to have broken the release. 
-yml file changes, so can not test locally.
> fix: Pin conventional commits to version 7

- .github/workflows/daily.yml
- change conventional commits to version 7 into daily yml file, there was major version bump to 8 on 5/03/2024, which seems to have broken the release.
- yml file changes, so can not test locally.
> fix: Pin conventional commits to version 7 to daily yml

- android-core/src/main/java/com/mparticle/internal/DeviceAttributes.java
- android-core/src/main/java/com/mparticle/internal/MPUtility.java
- android-core/src/test/kotlin/com/mparticle/internal/MPUtilityTest.kt
-Resolved StrictMode error by replacing direct usage of application context's WindowManager with DisplayMetrics.
- Tested locally
- Closes https://go.mparticle.com/work/SQDSDKS-6262
> fix: Use DisplayMetrics instead of WindowManager for StrictMode Error

- android-core/src/main/java/com/mparticle/networking/NetworkConnection.java
- android-core/src/main/java/com/mparticle/networking/NetworkOptions.java
- Added an option to disable certificate pinning, even in production.
- Tested with sample application
- Bad certificate and pinning option is false ( no response from the api)
- Bad certificate and pinning option is true 
- Closes https://go.mparticle.com/work/SQDSDKS-6541
> feat: Add option to disable certificate pinning

- android-core/src/main/java/com/mparticle/internal/MPUtility.java
- android-core/src/test/kotlin/com/mparticle/internal/MPUtilityTest.kt
- Move the code for retrieving the Google AD ID from a separate thread to the main thread. On some OS, running it in a separate thread causes the main thread to be delayed. (Revert Changes from PR #491 )
- Test with a sample app on Android os 14 and 15 using the simulator.
- Closes https://go.mparticle.com/work/SQDSDKS-6594
> fix: Remove Code for Handling Google AdId on a Separate Thread

- android-kit-base/src/main/java/com/mparticle/kits/KitConfiguration.java
- android-kit-base/src/test/kotlin/com/mparticle/kits/KitConfigurationTest.kt
- testutils/src/main/java/com/mparticle/mock/MockKitConfiguration.java
- Fix rare crash in KitConfiguration caused by NumberFormatException. Updated code to handle NumberFormatException and null cases.
- Tested with the sample application and could not reproduce the issue initially. However, after adding a unit test, I was able to reproduce the issue and address it.
- Closes https://go.mparticle.com/work/SQDSDKS-6548
> fix: Crash in KitConfiguration due to NumberFormatException

- android-core/src/androidTest/kotlin/com.mparticle/networking/NetworkOptionsManagerTest.kt
- android-core/src/main/java/com/mparticle/internal/Constants.java
- android-core/src/main/java/com/mparticle/networking/NetworkConnection.java
- android-core/src/main/java/com/mparticle/networking/NetworkOptions.java
- android-core/src/main/java/com/mparticle/networking/NetworkOptionsManager.java
- android-core/src/test/java/com/mparticle/networking/MParticleBaseClientImplTest.java
- Update Root Certificates
- Tested with a sample app and used domain mapping to test Let's Encrypt certificates.
- Closes https://go.mparticle.com/work/SQDSDKS-6546
> feat: Certificate pinning update

- android-core/src/androidTest/kotlin/com.mparticle/internal/BatchSessionInfoTest.kt
- android-core/src/main/java/com/mparticle/internal/ConfigManager.java
- android-core/src/main/java/com/mparticle/internal/Constants.java
- android-core/src/main/java/com/mparticle/internal/MParticleApiClientImpl.java
- android-core/src/main/java/com/mparticle/internal/MessageBatch.java
- android-core/src/main/java/com/mparticle/internal/UploadHandler.java
- android-core/src/main/java/com/mparticle/internal/database/services/MParticleDBManager.java
- android-core/src/test/kotlin/com/mparticle/internal/ConfigManagerTest.kt
- android-core/src/test/kotlin/com/mparticle/internal/UploadHandlerTest.kt
Remove unused session history upload code. Confirmed that this hasn't been used for years and can be safely removed.
- All unit tests pass and E2E tested in a sample app to see batches still uploading correctly.
- Closes https://go.mparticle.com/work/SQDSDKS-6788
> refactor: Remove unused session history upload code

- android-kit-base/src/test/kotlin/com/mparticle/kits/KitManagerImplTest.kt
- Fix the test case related to the migration to Kotlin.
-Executed local unit test cases
- Closes https://go.mparticle.com/work/SQDSDKS-6811
> fix: Testcase related to code refactor

- android-core/build.gradle
- android-core/src/androidTest/kotlin/com.mparticle/internal/AppStateManagerInstrumentedTest.kt
- android-core/src/main/java/com/mparticle/internal/MPUtility.java
- android-core/src/main/kotlin/com/mparticle/internal/AppStateManager.kt
- android-core/src/test/kotlin/com/mparticle/internal/AppStateManagerTest.kt
- Fix a bug where the previous Google app ID is null when the app is relaunched. This happened because the app ID was stored when the app paused; now, the code has been moved to when the app is in the foreground.
- Tested with sample app and Executed unit test cases
- Closes https://go.mparticle.com/work/SQDSDKS-6830
> fix: previous Google ad Id from being null on cold launch

- .github/workflows/cross-platform-tests.yml
It looks like macos-12 has been deprecated, per the error here https://github.com/mParticle/mparticle-android-sdk/actions/runs/12261598641/job/34492232250?pr=526
> ci: Update cross-platform-tests.yml

- .github/workflows/cross-platform-tests.yml
- .github/workflows/daily.yml
- .github/workflows/pull-request.yml
- Updated the GitHub Actions workflow to use the version tag 'v2' instead of a specific commit hash for emulator . 
> ci: update emulator version tag

- .github/workflows/pull-request.yml
- android-core/src/main/kotlin/com/mparticle/internal/JellybeanHelper.kt
- android-core/src/main/kotlin/com/mparticle/internal/KitKatHelper.kt
- cherry-pick commit https://github.com/mParticle/mparticle-android-sdk/pull/515
-Tested with sample app
- Closes https://go.mparticle.com/work/SQDSDKS-6712
> refactor: Migrate Internal OS Helper class to kotlin (#515)

- android-core/src/androidTest/kotlin/com.mparticle/MParticleTest.kt
- android-core/src/main/java/com/mparticle/MParticle.java
- Fix issue where previous location details were still being sent after calling `disableLocationTracking()`. Now, setLocation is set to null to clear the previous location.
- Tested with sample app
- Closes https://go.mparticle.com/work/SQDSDKS-7031
> fix: Disable location tracking to stop setting location updates

- settings-kits.gradle
- Remove Pilgrim-kit from cross-platform testing due to recent changes. Commented it out in settings-kit.gradle to avoid compatibility testing failures.
> ci: Remove Pilgrim-kit from cross-platform testing

- android-core/build.gradle
- android-core/src/androidTest/kotlin/com.mparticle/internal/AppStateManagerInstrumentedTest.kt
- android-core/src/main/java/com/mparticle/internal/MPUtility.java
- android-core/src/main/kotlin/com/mparticle/internal/AppStateManager.kt
- android-core/src/test/kotlin/com/mparticle/internal/AppStateManagerTest.kt
- cherry-pick commit https://github.com/mParticle/mparticle-android-sdk/pull/518
- Tested with sample app and Executed unit test cases
- Closes https://go.mparticle.com/work/SQDSDKS-6830
> fix: previous Google ad Id from being null on cold launch (#518)

- .github/workflows/daily.yml
- Downgraded API level to 28 to resolve java.lang.IllegalAccessError caused by com.android.library with API level 29 and above in Android Gradle 7
> ci: Downgrade API level to 28 for daily yml file

- .github/workflows/daily.yml
- This change removes the need to pass -PisRelease=true when running Gradle commands.
- Tested locally 
> ci: Remove manual build variant detection via isRelease flag

- .github/workflows/daily.yml
- This change makes it so you no longer need to add -PisRelease=true when running build commands.
> ci: Remove need for -PisRelease=true flag in Gradle command

- .github/workflows/daily.yml
- Tests are passing locally but consistently timing out in GitHub Actions. To unblock the pipeline, the affected instrumentation tests are commented out for now. 
- All the test locally tested.
> fix: Disable instrumentation tests temporarily

- .gitmodules
- Fix Git submodule error related to Rokt Kit integration
> fix: Rokt Submodule link

- android-core/proguard.pro
- This commit adds a ProGuard rule to preserve the visibility of specific methods during the release build.
- Tested with local release build with sample app
> fix: Add ProGuard rule to preserve method visibility

- android-core/src/main/java/com/mparticle/MParticleOptions.java
- android-kit-base/src/main/java/com/mparticle/kits/KitIntegrationFactory.java
- android-kit-base/src/test/kotlin/com/mparticle/kits/KitManagerImplTest.kt
- This PR introduces a new option in MParticleOptions that allows users to disable specific kits. When a kit is disabled, it will not be initialized, and no events will be sent from that kit.
- Tested locally using a release build and executed the unit test cases.
- Closes https://go.mparticle.com/work/SQDSDKS-7219
> feat: Add option to disable kits in MParticleOptions

- android-kit-base/src/main/java/com/mparticle/kits/KitConfiguration.java
- android-kit-base/src/main/java/com/mparticle/kits/KitManagerImpl.java
- android-kit-base/src/test/kotlin/com/mparticle/kits/KitManagerImplTest.kt
- Implement user attribute transformation based on placement mapping in Rokt execute
- Tested With sample app and Executed unit test cases
- Closes https://go.mparticle.com/work/SQDSDKS-7185
> feat: Add user attributes mapping logic in Rokt execute flow

- android-core/src/main/java/com/mparticle/MParticle.java
- This PR adds the `@NonNull` and `@Nullable` annotations to execute method parameters. This update helps make the method's expectations clearer and improves null-safety in the code.
- Tested with sample app
> fix: Add @NonNull and @Nullable annotations to execute method parameters

- android-core/src/main/kotlin/com/mparticle/rokt/RoktEmbeddedView.kt
- android-core/src/main/kotlin/com/mparticle/rokt/RoktLayoutDimensionCallBack.kt
- This PR adds the Rokt dimensions layout to resolve the issue with the Rokt widget not displaying correctly. The update ensures proper layout handling and fix widget-related issues.
- Tested with sample app.
> fix: add Rokt dimensions layout to show embedded placements correctly

- android-core/src/main/java/com/mparticle/MParticle.java
- android-core/src/main/java/com/mparticle/internal/KitFrameworkWrapper.java
- android-core/src/main/java/com/mparticle/internal/KitManager.java
- android-core/src/main/kotlin/com/mparticle/rokt/RoktConfig.kt
- android-core/src/test/kotlin/com/mparticle/MParticleTest.kt
- android-kit-base/src/main/java/com/mparticle/kits/KitIntegration.java
- android-kit-base/src/main/java/com/mparticle/kits/KitManagerImpl.java
- android-kit-base/src/test/kotlin/com/mparticle/kits/KitManagerImplTest.kt
- Add Rokt Config to the MP core layer
- Tested with sample App and Executed test cases
- Closes https://go.mparticle.com/work/SQDSDKS-7384
> feat: Add RoktConfig in MP layer

- android-kit-base/src/main/java/com/mparticle/kits/KitManagerImpl.java
- This PR update makes sure that user attributes are fully saved before moving to the next step.
It uses a callback with getUserAttributes to wait until the data is ready.
This helps avoid problems where Rokt tries to use user info before it's updated.
- Tested with sample app
> fix: ensure user attributes are applied before proceeding with Rokt execution

- kit-plugin/src/main/groovy/com/mparticle/kits/KitPlugin.groovy
- This PR migrates our artifact publishing workflow from OSSRH (The Open Source Software Repository Hosting) to the new Central Publishing Portal (CPP) as per the updated guidelines from Sonatype.
Guideline : https://central.sonatype.org/news/20250326_ossrh_sunset/
- Closes https://go.mparticle.com/work/SQDSDKS-7479
> chore: Update kit plugin publishing URL from OSSRH to CPP

- android-core/src/main/java/com/mparticle/internal/KitFrameworkWrapper.java
- android-core/src/main/java/com/mparticle/internal/KitManager.java
- android-core/src/main/kotlin/com/mparticle/Rokt.kt
- android-kit-base/src/main/java/com/mparticle/kits/KitIntegration.java
- android-kit-base/src/main/java/com/mparticle/kits/KitManagerImpl.java
- android-kit-base/src/test/kotlin/com/mparticle/kits/KitManagerImplTest.kt
- Map Rokt.close through to Rokt Kit
- Works in conjunction with mparticle-integrations/mparticle-android-integration-rokt#49
- Tested as part of mParticle/mparticle-android-sample-apps#279
- Closes https://go.mparticle.com/work/SQDSDKS-7444
> feat: Add Rokt close implementation

- android-core/src/main/kotlin/com/mparticle/Rokt.kt
- Previously, selectPlacement assumed attributes were always mutable. When an immutable map was passed, it caused issues if modifications were required during processing.Created a shallow copy of attributes before passing it to execute.This ensures compatibility with both immutable and mutable inputs.
- Tested with sample app for both immutable and mutable inputs.
> fix: Support mutable and immutable attributes in selectPlacement
